### ISSUE TITLE
Fix HP of Dark Soldiers and Dark Archers

### ISSUE THREAD

**Issue by Kn1MS** [Vasar007/TIMLE#8]
**Is your feature request related to a problem? Please describe.**
This feature request is related to balance problem. The hp of two creatures in the game is too high and needs to be reduced.

**Describe the solution you'd like**
Instead of 1000 and 200 hp respectively for Dark Soldiers and Dark Archers it would be better to make 100 hp for Soldiers and 150 for Archers.

**Describe alternatives you've considered**
None.

**Additional context**
With nearly unlimited hp dark soldiers become more of a nuisance than a regular enemy.
Archers need to be squishier being one of the most dangerous enemies in the game. They already pose a serious threat with their presence itself, there is no need to make them too tough.

**Comment by Vasar007** [comment]
Can you edit your issue in following form

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

?
